/**
 * "The Second Copy" — hand-authored design fixtures.
 *
 * These are DESIGN FIXTURES. `source_kind` is `design_fixture` in every
 * influence record and must stay that way until real captured evidence and a
 * real recorded approval replace it. Nothing here was retrieved from Qloo,
 * generated by a model, or produced by any external service: there is no
 * entity UUID, no retrieval timestamp, and no API metadata in these files.
 *
 * The three versions share one world and one clean core. Only the Discovery
 * module differs between v1 and v2, which is what makes the same-choices
 * comparison meaningful.
 */

import { parseBrief } from "../src/domain/brief";
import type { Brief } from "../src/domain/brief";
import { parseScene } from "../src/domain/scene";
import type { Id, Scene } from "../src/domain/scene";
import baseJson from "./second_copy.base.json";
import briefJson from "./second_copy.brief.json";
import discoveryV1Json from "./second_copy.discovery_v1.json";
import discoveryV2Json from "./second_copy.discovery_v2.json";

export const SECOND_COPY_BRIEF: Brief = parseBrief(briefJson);

/** Parsed at module load, so an invalid fixture can never reach the player. */
export const SECOND_COPY_BASE: Scene = parseScene(baseJson);
export const SECOND_COPY_DISCOVERY_V1: Scene = parseScene(discoveryV1Json);
export const SECOND_COPY_DISCOVERY_V2: Scene = parseScene(discoveryV2Json);

export type VersionKey = "base" | "v1" | "v2";

export type FixtureVersion = {
  readonly key: VersionKey;
  readonly label: string;
  readonly note: string;
  readonly scene: Scene;
};

export const SECOND_COPY_VERSIONS: readonly FixtureVersion[] = [
  {
    key: "base",
    label: "Without this influence",
    note:
      "The clean brief-only foundation, with no influence module composed. This is an ablation, not a creative competitor.",
    scene: SECOND_COPY_BASE,
  },
  {
    key: "v1",
    label: "Discovery v1",
    note:
      "Approved interpretation: inspection reveals an identity contradiction, and discussing it is required before returning the letter.",
    scene: SECOND_COPY_DISCOVERY_V1,
  },
  {
    key: "v2",
    label: "Discovery v2 · saved revision",
    note:
      "The one approved revision: raising the contradiction makes Nia refuse the letter, so it can be returned before that question but not afterwards.",
    scene: SECOND_COPY_DISCOVERY_V2,
  },
];

export function versionByKey(key: VersionKey): FixtureVersion {
  const found = SECOND_COPY_VERSIONS.find((version) => version.key === key);
  if (found === undefined) throw new Error(`unknown version "${key}"`);
  return found;
}

/**
 * The canonical same-choices comparison from specification section 15:
 * inspect -> ask why she came back -> ask about the two names.
 */
export const CANONICAL_REPLAY_PREFIX: readonly Id[] = [
  "core.inspect",
  "core.ask_context",
  "discovery.ask_identity",
];

/**
 * The approvals a frozen snapshot would hold for these fixtures. Phase 1 has
 * no database, so this list is the local stand-in that lets the validator
 * prove a scene cannot authorize an approval the snapshot does not contain.
 */
export const APPROVED_APPROVAL_IDS: readonly Id[] = [
  "approval_discovery_v1",
  "approval_discovery_v2",
];
